kind: Service
apiVersion: v1
metadata:
  name: clusterip-service
spec:
#  type: ClusterIP # 생략가능, 기본값=CluseterIP
#  clusterIP: 10.233.10.10 # 생략 가능, 10.233.0.0/18에서 자동 할당
  selector:
    app: webui
  ports:
  - port: 80
    targetPort: 80 